name: 'Print PDF'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  print:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      
    - name: Install Puppeteer Libraries
      run: |
        sudo apt-get update
        sudo apt-get install -yq libatk1.0-0 libc6 libcairo2 \
        libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 \
        libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 \
        libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 \
        libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 \
        libxss1 libxtst6 ca-certificates fonts-liberation libnss3 lsb-release \
        xdg-utils wget

    - uses: actions/checkout@v2

    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.2.0

    - name: Install dependencies
      run: bun install --frozen-lockfile

    - name: Build
      run: bun run build

    - name: Start development server
      run: bun preview &
      env:
        HOST: 0.0.0.0  

    - name: Generate PDF
      run: bun print
      env:
        FULLNAME: ${{ vars.FULLNAME }}
        PRINT_PORT: 4173

    - name: Commit and push if changed
      run: |-
        git diff
        git config --global user.email "pdf-bot@example.com"
        git config --global user.name "PDF-bot"
        git add -A
        git commit -m "Updated Resume" || exit 0
        git push
