name: 'Print PDF'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  print:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      
    - name: Install Puppeteer Libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y libgbm1
        
    - uses: actions/checkout@v2

    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.2.0

    - name: Install dependencies
      run: bun install --frozen-lockfile

    - name: Start development server
      run: bun run dev &
      env:
        HOST: 0.0.0.0  

    - name: Wait for port 5173
      uses: fountainhead/action-wait-for-check@v1
      with:
        type: tcp
        address: 0.0.0.0
        port: 5173
        timeout: 60

    - name: Generate PDF
      run: bun print

    - name: Commit and push if changed
      run: |-
        git diff
        git config --global user.email "pdf-bot@example.com"
        git config --global user.name "PDF-bot"
        git add -A
        git commit -m "Updated Resume" || exit 0
        git push
