name: 'Generate Resume'

on:
  push:
    branches: [main]

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      
    - name: Install Puppeteer Libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y libgbm1

    - uses: actions/checkout@v2

    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.2.0

    - name: Install dependencies
      run: bun install --frozen-lockfile

    - name: Build app
      run: bun run build

    - name: Start server
      run: bun preview &
      env:
        HOST: 0.0.0.0  

    - name: Generate Resume
      run: bun generate
      env:
        FULLNAME: ${{ vars.FULLNAME }}
        PRINT_PORT: 4173

    - name: Commit and push if changed
      run: |-
        git diff
        git config --global user.email "resume-bot@example.com"
        git config --global user.name "resume-bot"
        git add -A
        git commit -m "Updated Resume" || exit 0
        git push
